# Generated by Django 4.0.3 on 2022-05-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeWeb', '0002_resume_user_id_alter_resume_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='user',
        ),
    ]
