# Generated by Django 4.1.7 on 2023-03-23 14:58

import ResumeWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeWeb', '0003_rename_user_id_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ResumeWeb.models.upload_and_rename),
        ),
    ]
