# Generated by Django 4.1.7 on 2023-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeWeb', '0005_alter_resume_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
